#!/bin/bash
# This deploy hook gets executed after dependencies are resolved and the
# build hook has been run but before the application has been started back
# up again.  This script gets executed directly, so it could be python, php,
# ruby, etc.

# TODO error here
source "${OPENSHIFT_HOMEDIR}"python/virtenv/bin/activate

# GETTING-STARTED: change 'db.sqlite3' to your sqlite3 database:
if [ ! -f $OPENSHIFT_DATA_DIR/db.sqlite3 ]
then
    echo "Copying $OPENSHIFT_REPO_DIR/wsgi/zoomingdevices/db.sqlite3 to $OPENSHIFT_DATA_DIR"
    cp "$OPENSHIFT_REPO_DIR"wsgi/zoomingdevices/db.sqlite3 $OPENSHIFT_DATA_DIR
    python "$OPENSHIFT_REPO_DIR".openshift/action_hooks/secure_db.py | tee ${OPENSHIFT_DATA_DIR}/CREDENTIALS
else
    echo "Executing 'python $OPENSHIFT_REPO_DIR/wsgi/zoomingdevices/manage.py migrate'"
    python "$OPENSHIFT_REPO_DIR"wsgi/zoomingdevices/manage.py syncdb --noinput
fi

echo "Executing 'python $OPENSHIFT_REPO_DIR/wsgi/zoomingdevices/manage.py collectstatic'"
python "$OPENSHIFT_REPO_DIR"wsgi/zoomingdevices/manage.py collectstatic --noinput
